// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfmxrcrlxvmuxlmvuwud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmbXhyY3JseHZtdXhsbXZ1d3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDYzNDUsImV4cCI6MjA2OTI4MjM0NX0.2-OOhHqDMV7r4Td8bys7IvdOx5KdTG3mzYOJYJDVPUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});